version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB:   ${DATABASE_NAME}
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      retries: 5

  rentcarback:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_PORT: ${APP_PORT}
        NODE_ENV: ${NODE_ENV}
    depends_on:
      database:
        condition: service_healthy
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      APP_PORT: ${APP_PORT}
      NODE_ENV: ${NODE_ENV}
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - ./:/opt/application
      - /opt/application/node_modules
