
###
run ../cars/list.http

###
run ../users/create.http

###
run ../auth/sign-in.http

###
# @name BOOKINGS_CREATE

POST http://localhost:3000/bookings
Authorization: Bearer {{AUTH_SIGN_IN.response.body.$.access_token}}
Content-Type: application/json

{

    "carId": "{{CARS_LIST.response.body.$.data[0].id}}",
    "userId": "{{USERS_CREATE.response.body.$.id}}",
    "startDate": "2025-04-02T16:10:59.840Z",
    "endDate": "2025-05-02T16:10:59.840Z"
}
